dataset: "voicemos2023" # name of the dataset
datapath: /media/shenkailai/ubuntu/VoiceMOS2023 # path to the dataset
output_dir: ./output # path to the directory where the results will be saved
pretrained_model: # 


# Dataset options
csv_file: voicemos2023_mean.csv # csv-file with MOS labels and filepaths of all datasets, must be placed in 'data_dir', must contain columns 'mos', 'noi', 'dis', 'col', 'loud' with overall and dimension quality ratings
csv_deg: filename # csv column name of filepath to degraded speech sample, path must be relative to 'data_dir'
csv_user_ID : user_ID # csv column name of user ID
csv_mos_train: mos # csv column name of target training value (usually MOS)
csv_mean_train: mean_mos # csv column name of target training value (usually MOS)
csv_mos_val: mos # csv column name of target validation value (usually MOS)
csv_db_train: # dataset names of training sets, the dataset names must be in 'db' column of csv file
    - VoiceMOS2022_main_Train
    - VoiceMOS2022_OOD_Train

    
csv_db_val:  # dataset names of validation sets, the dataset names must be in 'db' column of csv file
    - VoiceMOS2022_main_Dev
    - VoiceMOS2022_OOD_Dev

csv_db_test:  # dataset names of test sets, the dataset names must be in 'db' column of csv file
    - VoiceMOS2022_main_Test
    - VoiceMOS2022_OOD_Test1
    - VoiceMOS2022_OOD_Unlabeled1

to_memory: false # load the whole dataset to the memory
to_memory_workers: 0 # number of workers for the dataloader
comment: "use_biasloss_new" # comment for the experiment

# Data augmentation options
target_length: 1024 # length of the target signal
mel_bins: 128 # number of mel bins
skip_norm: false # skip normalization

train_norm_mean: -7.0234294 
train_norm_std: 4.659489 
val_norm_mean: -8.346359 
val_norm_std: 4.475686 
test_norm_mean: -6.3182464
test_norm_std: 4.0547657

# Training parameters
batch_size: 8 # batch size
num-workers: 16 # number of workers for the dataloader
n-epochs: 100 # number of epochs
seed: 20 # seed for the random number generator
tr_parallel: false # use parallel training
tr_lr: 1e-5 # learning rate
tr_wd: 1e-5 # weight decay

# SSAST parameters
fstride: 16 # stride of the feature map
tstride: 16 # stride of the temporal dimension
fshape: 16 # shape of the feature map
tshape: 16 # shape of the temporal dimension
load_pretrained_mdl_path: pre_models/SSAST-Base-Patch-400.pth # path to the pretrained model
model_size: "base" # size of the model

# TAB parameters
num_tab: 2


# SQAloss parameters
loss_type: "mae" # loss function type
alpha: [1, 0] # weights for the loss
beta: [.1, .1, 1] # weights for the loss
p: 2 # p for the loss
q: 2 # q for the loss
monotonicity_regularization: false # use monotonicity regularization
gamma: 0.1 # gamma for the monotonicity regularization
detach: false # detach the prediction from the graph


# Hallucination parameters
hallucinate: false # use hallucination
att_method: "luong" # attention method
apply_att_method: "hard" # apply attention

# Bias loss options (optional)
tr_bias_mapping: first_order # set to 'first_order' if bias loss should be applied, otherwise 'null'
tr_bias_min_r: 0.7 # minimum correlation threshold to be reached before estimating bias (e.g. 0.7), set to 'null' if no bias loss should be applied
tr_bias_anchor_db: null # name of anchor dataset (optional)
tr_verbose: 2 
use_biasloss: false

# Database normalization statistics (moved from hardcoded values)
norm_stats:
  NISQA_TEST_LIVETALK:
    nisqa: [-9.051971, 3.7531793]
  NISQA_TEST_FOR:
    nisqa: [-8.937617, 4.2769117]
  NISQA_TEST_P501:
    nisqa: [-9.90131, 4.708985]
  NISQA_VAL_LIVE:
    nisqa: [-9.823734, 3.6818407]
  NISQA_VAL_SIM:
    nisqa: [-8.027123, 4.3762627]
  NISQA_VAL:
    nisqa: [-8.185567, 4.3552947]
  tencent_with:
    tencent: [-8.642287, 4.199733]
  tencent_without:
    tencent: [-9.084293, 5.4488106]
  TMHINTQI_Valid:
    voicemos2023: [-4.865034, 4.1673865]
  VoiceMOS2022_mian_Test:
    voicemos2023: [-8.353344, 4.4906945]
  VoiceMOS2022_OOD_unlabeled1:
    voicemos2023: [-7.7979817, 4.426462]
  VoiceMOS2022_OOD_Test1:
    voicemos2023: [-7.64568, 4.315633]